import { NetworkType } from "../core/chains";

export enum TokenType {
  NO_TOKEN,
  NORMAL_TOKEN,
  CURVE_LP_TOKEN,
  YEARN_ON_NORMAL_TOKEN,
  YEARN_ON_CURVE_TOKEN,
  CONVEX_LP_TOKEN,
  CONVEX_STAKED_TOKEN,
  DIESEL_LP_TOKEN,
  GEAR_TOKEN,
  COMPOUND_V2_C_TOKEN,
  BALANCER_LP_TOKEN,
  AAVE_V2_A_TOKEN,
  WRAPPED_AAVE_V2_TOKEN,
  ERC4626_VAULT_TOKEN,
  WRAPPED_TOKEN,
  AURA_LP_TOKEN,
  AURA_STAKED_TOKEN,
  CONVEX_L2_STAKED_TOKEN,
  ZIRCUIT_STAKED_TOKEN,
  STAKING_REWARDS_PHANTOM_TOKEN,
}

export enum PhantomTokenType {
  NO_TOKEN,
  CONVEX_PHANTOM_TOKEN,
  ZIRCUIT_PHANTOM_TOKEN,
  STAKING_REWARDS_PHANTOM_TOKEN,
}

export type TokenNetwork = NetworkType | "AllNetworks";
