export const CREDIT_MANAGER_GROUP = "CREDIT_MANAGER";
export const TOKEN_GROUP = "TOKEN";
export const PRICE_FEED_GROUP = "PRICE_FEED";
export const POOL_GROUP = "POOL";
export const PRICE_ORACLE_GROUP = "PRICE_ORACLE";

export const ALL_GROUPS = [
  CREDIT_MANAGER_GROUP,
  TOKEN_GROUP,
  PRICE_FEED_GROUP,
  POOL_GROUP,
  PRICE_ORACLE_GROUP,
] as const;

export type PolicyGroup = (typeof ALL_GROUPS)[number];

export type ControllableParam =
  | "EXPIRATION_DATE"
  | "MAX_DEBT_PER_BLOCK_MULTIPLIER"
  | "MIN_DEBT"
  | "MAX_DEBT"
  | "CREDIT_MANAGER_DEBT_LIMIT"
  | "TOKEN_LT"
  | "FORBID_ADAPTER"
  | "LP_PRICE_FEED_LIMITER"
  | "TOKEN_LIMIT"
  | "TOKEN_QUOTA_INCREASE_FEE"
  | "TOKEN_QUOTA_MIN_RATE"
  | "TOKEN_QUOTA_MAX_RATE"
  | "RESERVE_PRICE_FEED_STATUS"
  | "TOTAL_DEBT_LIMIT"
  | "WITHDRAW_FEE";

export type PolicyKey = PolicyGroup | ControllableParam;

export const POLICY_KEYS: Record<ControllableParam, Array<PolicyKey>> = {
  EXPIRATION_DATE: ["CREDIT_MANAGER", "EXPIRATION_DATE"],
  LP_PRICE_FEED_LIMITER: ["PRICE_FEED", "LP_PRICE_FEED_LIMITER"],

  MAX_DEBT_PER_BLOCK_MULTIPLIER: [
    "CREDIT_MANAGER",
    "MAX_DEBT_PER_BLOCK_MULTIPLIER",
  ],

  MIN_DEBT: ["CREDIT_MANAGER", "MIN_DEBT"],
  MAX_DEBT: ["CREDIT_MANAGER", "MAX_DEBT"],
  CREDIT_MANAGER_DEBT_LIMIT: ["CREDIT_MANAGER", "CREDIT_MANAGER_DEBT_LIMIT"],
  TOKEN_LT: ["CREDIT_MANAGER", "TOKEN", "TOKEN_LT"],
  FORBID_ADAPTER: ["CREDIT_MANAGER", "FORBID_ADAPTER"],
  TOKEN_LIMIT: ["POOL", "TOKEN", "TOKEN_LIMIT"],
  TOKEN_QUOTA_INCREASE_FEE: ["POOL", "TOKEN", "TOKEN_QUOTA_INCREASE_FEE"],
  TOTAL_DEBT_LIMIT: ["POOL", "TOTAL_DEBT_LIMIT"],

  WITHDRAW_FEE: ["POOL", "WITHDRAW_FEE"],
  TOKEN_QUOTA_MIN_RATE: ["POOL", "TOKEN", "TOKEN_QUOTA_MIN_RATE"],
  TOKEN_QUOTA_MAX_RATE: ["POOL", "TOKEN", "TOKEN_QUOTA_MAX_RATE"],
  RESERVE_PRICE_FEED_STATUS: [
    "PRICE_ORACLE",
    "TOKEN",
    "RESERVE_PRICE_FEED_STATUS",
  ],
};
